### ISSUE TITLE
iOS: Parts of the pdf viewer are behind the title

### ISSUE THREAD

**Issue by scthi** [trigger-corp/trigger.io-tabs#20]
Please see the screenshot below. The zoom indicator? is covered by the title bar.

Device: iPhone 8 Max - iOS 12.4.1
Device: iPhone 8 - iOS 13.1.2
Tabs Module Version: 3.2

<details>
<img src="https://user-images.githubusercontent.com/318533/68873316-bd440480-06ff-11ea-805c-56440abb1177.jpeg"/>
</details>

**Comment by antoinevg** [comment]
Ugh… Apple aren't respecting SafeAreaInsets for their own PDF viewer. That button should have been laid out relative to SafeAreaInsets rather than the top of the PDF view.

**Comment by scthi** [comment]
@antoinevg Do you see the chance to workaround this?

**Comment by antoinevg** [comment]
Weirdly enough I may have found a solution this morning while fixing some unrelated layout bugs introduced by iOS 13.2.x

If you can live without the topbar/statusbar translucency effects you can use the `opaqueTopBar` property to work around it:

```javascript
forge.tabs.openAdvanced({
    url: "https://ops.trigger.io/75d92dce/tests/test.pdf",
    opaqueTopBar: true
}, ...
```

**Comment by scthi** [comment]
@antoinevg Cool, this seems indeed to correct the layouting. Unfortunately the `tint` property isn't working anymore:

```js
forge.tabs.openAdvanced({
    url: "https://ops.trigger.io/75d92dce/tests/test.pdf",
    opaqueTopBar: true,
    tint: [75, 0, 0, 255]
}, ...
```

still has a white background...

**Comment by antoinevg** [comment]
No iOS release cycle would be complete without Apple once again changing the way navigation and status bar colouring works :-)

Can you please try against module version `3.4.2` ?

**Comment by scthi** [comment]
My first tests look very promising with 3.4.2

**Comment by scthi** [comment]
@antoinevg A colleague noticed a small issue while testing. We use a bottom up slide animation to open the tab. During the animation, the header background color is white and the configured `tint` color is applied as soon as the tab is fully visible... which is not so nice. 🙈

Please let me know if you need further information.

🤔Mby it would work when setting the tint already in `viewWillDisappear` instead of `viewDidAppear`:
https://github.com/trigger-corp/trigger.io-tabs/compare/v3.3...v3.4.2#diff-c8134ce8adb5638f2f80373e27b30d32R132

**Comment by antoinevg** [comment]
I tried it the other way round initially, it looks much worse as the navbar and statusbar colors then get applied at different times (!)

The underlying problem is that Apple have never provided any official API's to work with statusbar tints so it's always a hack when you want to get things to match up. :-/

The cleanest result you'll get is if you just keep the status & navbars at their default colours and not try to set a tint.

**Comment by scthi** [comment]
Ah, I see. Thanks for the clarification. 👍 

Do you think making the statusbar transparent (or hiding it) during the animation might be better? 🤔

**Comment by prud** [comment]
Oh too bad :/ Any chance that the color tint could be applied directly, whereas the fix for the top offset issue is applied after some time? No idea how each of them works technically and what limitations there are, just looking for a more graceful solution as our customers are very sensitive reg. the branding colors of the header bar :-/

**Comment by antoinevg** [comment]
That's not how it works.

To sum things up one last time:

1. The root cause of the issue is that Apple aren't laying out their pdf viewer taking safe area insets into account.
2. A workaround to this is to disable translucent status bars. This workaround works by removing the impact of the safe area inset as now the drawable area starts below the navigation bar rather than the top of the screen.
3. However: Since Apple introduced the notch their philosophy says that the only thing which exists is a unified translucent status and navigation bar which can both be tinted by setting the colour of the navigation bar.
4. This means that opaque navigation and status bars are:
  a. non-standard in Apple's philosophy of API design 
  b. Apple are not going to provide an official way of setting the status bar colours
  c. there isn't a concept of setting the nav and status bar colours simultaneously.
5. So you are very lucky I spent the time to figure out this hack to work around an otherwise unsolvable bug caused by Apple's developers.

This is also why I said:

> The cleanest result you'll get is if you just keep the status & navbars at their default colours and not try to set a tint.

That said, I'm more than happy to accept pull requests if you can come up with a better set of trade-offs to get the result you're looking for without breaking the rest of the module.

**Comment by prud** [comment]
Arg, okay makes sense, thanks for the clarification 👍

**Comment by scthi** [comment]
@antoinevg I think I found a solution for the tinting issue: https://github.com/trigger-corp/trigger.io-tabs/pull/27

I'd be happy about your feedback.

**Comment by scthi** [comment]
PR landed in master.
